version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./days:/aoc/days
    ports:
      - "5432:5432"
